export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE_LOGIN = "SET_MESSAGE_LOGIN";

export const SET_MESSAGE_REGISTER = "SET_MESSAGE_REGISTER";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOADING = "LOADING"
